services:
  - type: web
    name: waqf-scraper
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh && chmod +x ./start.sh
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    numInstances: 1
    disk:
      name: pdf-storage
      mountPath: /opt/render/project/src/backend/pdf_output
      sizeGB: 1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
